# Numpy

In [ ]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
## 1d array
arr1 = np.array([2,4,6,8])
print(arr1)
print(arr1.shape)
arr1.reshape(2,2)

[2 4 6 8]
(4,)


array([[2, 4],
       [6, 8]])

In [7]:
arr2 = np.array([[2,4,6,8],[1,3,5,7]])
print(arr2.shape)
print(arr2)

(2, 4)
[[2 4 6 8]
 [1 3 5 7]]


In [18]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
arr2 = np.arange(1,21).reshape(20,1)

In [45]:
print(arr2)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]]


In [47]:
for i in arr2:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [3]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
### numpy vectorize 

ar1 = np.array([4,6,4,6,7])
ar2 = np.array([5,6,4,7,3])

## element wise addition 
sum = ar1+ar2
print(sum)
## element wise subsraction
sub = ar1-ar2
print(sub)

[ 9 12  8 13 10]
[-1  0  0 -1  4]


In [17]:
## universal function
arr = np.array([4,6,3,16,9,81])

# square root 
print(np.sqrt(arr))

# exponential 
print(np.exp(arr))

# sine 
print(np.sin(arr))

# natural log
print(np.log(arr))

[2.         2.44948974 1.73205081 4.         3.         9.        ]
[5.45981500e+01 4.03428793e+02 2.00855369e+01 8.88611052e+06
 8.10308393e+03 1.50609731e+35]
[-0.7568025  -0.2794155   0.14112001 -0.28790332  0.41211849 -0.62988799]
[1.38629436 1.79175947 1.09861229 2.77258872 2.19722458 4.39444915]


In [38]:
# array slicing and indexing 
arr3 = np.array([[4,6,8],[4,5,3],[5,2,6]])

print(arr3[1:,1:2])
print(arr3[0][2])

[[5]
 [2]]
8


In [41]:
# statistical concept --normalization

arr4 = np.array([56,3,55,33,11,23,7,33])

## avarege 
print("mean :",np.mean(arr4))
#  median
print("median :",np.median(arr4))
## standard deviation
print("standard deivations :",np.std(arr4))
# variance
print("variance :",np.var(arr4))

mean : 27.625
median : 28.0
standard deivations : 19.176401513318392
variance : 367.734375


In [47]:
# logical operations

data = np.array([5,6,8,4,4,8,3])

result = data >=5
print(result)

get_data = data[data>=5]
print(get_data)

[ True  True  True False False  True False]
[5 6 8 8]


In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.full((2,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(b[1,2])

6


In [20]:
b[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [18]:
np.random.randint(1,10,(2,3))

array([[4, 3, 7],
       [2, 6, 3]], dtype=int32)

In [13]:
c = np.array([10,20,30,40,50,60,70,80,90])
c[c%4==0]


array([20, 40, 60, 80])